name: get_bootimg_from_payload.bin

on:
  watch:
    types: [started]
    

jobs:
  make:
    runs-on: ubuntu-latest

    steps:

    - name: install Python 3.7
      uses: actions/setup-python@v1
      with:
          python-version: 3.7
    - name: Initialization environment 
      run: |
        cd ~
        pip install bsdiff4
        python -m pip install protobuf

  
